var sport = [
    "Elvis Presley miał czarny pas w karate. Poznał je podczas swojej służby wojskowej w Niemczech. Niektóre ruchy wykorzystywał w swych układach tanecznych.",
    "Karate rozwinęło się z lokalnej sztuki walki z wysp Riukiu (dziś Japonia) pod wpływem chińskich sztuk walki. Królestwo Riukiu było niezależne od XV do XIX wieku. Mimo swojego małego rozmiaru, grało w średniowieczu dominującą rolę w handlu morskim wschodniej Azji. Do XIX wieku Królestwo Riukiu miało dużo więcej wspólnego z Chinami, niż z Japonią.",
    "W aikido nie ma punktowanych sparingów. Brak sparingów i rywalizacji jest krytykowany jako źródło słabości aikido, któremu zarzuca się oderwanie od realiów prawdziwej walki.",
    "Taekwondo, wraz z judo, jest sportem olimpijskim. Gyeorugi, czyli sparingi teakwondo, stanowią część programu olimpijskiego od roku 2000. Od lat trwają też zabiegi o wprowadzenie karate. Na 117 posiedzeniu MKOL w lipcu 2005 w karate otrzymało ponad połowę głosów, wobec wymaganej większości dwóch trzecich.",
    "Słowo \"karate\" oznacza dosłownie \"pusta ręka\". Karate powstało z lokalnych sztuk walki wysp Riukiu (w języku okinawskim nazywanych te) pod wpływem chińskich sztuk walki, w szczególności stylu żurawia.",
    "Słowo \"judo\" oznacza dosłownie \"łagodna droga\". Słowo składa się z dwóch kanji, \"ju\" oznaczającego \"łagodna\" (tak, jak w \"ju-jitsu\", czyli \"łagodnej sztuce\") oraz \"do\" oznaczającego \"drogę\".",
    "Taekkyon jest jedyną jeszcze praktykowaną sztuką walki wywodzącą się z antycznej sztuki subak i najprawdopodobniej uprawiany był już w czasie przed okresem Trzech Królestw Korei (57 p.n.e.–676). W okresie państwa Joseon (1392–1910) był rozpowszechniony we wszystkich warstwach społecznych. Zabroniony przez japońskie władze okupacyjne na początku lat 30. XX w. pod groźbą kary śmierci, Taekkyon odrodził się w Korei Południowej i został uznany przez władze za ważny element dziedzictwa kulturowego.",
    "Ninja posługiwali się mieczem o nazwie ninja-to (inaczej: shinobi-gatana) jako zamiennik dla katany. Nie używano go zbyt często, a jego wykonanie nie było tak kunsztowne i pracochłonne jak jego samurajskiego odpowiednika. Z tego powodu, ninja-to często się łamały w starciu z silniejszą bronią",
    "Klasztor Szaolin znajduje się w prowincji Henan. Jest to trzecia co do wielkości populacji prowincja Chin i jednocześnie matecznik cywilizacji chińskiej.",
    "Słowo \"kyokushin\" (jeden ze stylów karate) tłumaczone jest jako ekstremum prawdy. Od \"kyoku\" - ekstremum i \"shin\" - prawda",
    "Arnis to rdzenna filipińska sztuka walki, której nazwa pochodzi od hiszpańskiego słowa arnes, oznaczającego pancerz. W niektórych regionach Filipin jest ona bardziej znana jako escrima lub kali. Bronią stosowaną w tej sztuce są noże, składane noże motylkowe–Balisong, Dulo Dulo oraz kije, jeden lub dwa, o blisko metrowej długości. Uważa się, że właśnie przez mistrza tej sztuki walki, Lapu-Lapu, został zabity w 1521 r. na Mactan Ferdynand Magellan.",
    "Bokator to brutalna, khmerska sztuka walki wzorująca techniki na ruchach zwierząt. Nazwa oparta jest na dawnej legendzie, według której pewien wojownik miał bez użycia broni pokonać lwa. Ciekawostką jest, że w Bokatorze, możemy poznać aż 10 000 technik, co daje ogromną liczbę możliwych kombinacji.",
    "Edward Sell w roku 1963 został pierwszym Amerykaninem, któremu pozwolono uczestniczyć w Narodowych Mistrzostwach Korei. W 1997 otrzymał 9 dan od World Chung Do Kwan a w 2001 roku, 9 dan od World Taekwondo Federation. Był pierwszym mistrzem spoza Korei, który otrzymał tak wysoki stopień. Edward Sell napisał pierwszy amerykański podręcznik do treningu taekwondo.",
    "Gichin Funakoshi urodził się 10 listopada 1868 roku w Suri i jest uznawany za ojca współczesnego Karate. Masutasu Oyama pobierał nauki pod jego okiem, w następstwie tworząc inny styl Karate Kyokushin.",
    "Słowo Seonbae w j. koreańskim oznacza dosłownie: \"starsi\" , jest czasami tłumaczone jako \"człowiek cnoty, który nigdy nie wycofuje się z walki\". Było to określenie używane do oznaczenia wojowników krolestwa Goguryeo. Członkowie Seonbae żyli w grupach i uczyli się łucznictwa , zapasów Gakju i sztuki walki Subaka , historii, literatury i innych sztuk wyzwolonych . Goguryeo był jedną z wielkich potęg w Azji Wschodniej , aż do jej pokonania przez sojusz Silla-Tang w 668 r.",
    "Tonfa to pałka, która może być używana zarówno w obronie, jak i w ataku. Poprawnie trzymana jest niezastąpiona do blokowania nawet bardzo mocnych uderzeń. Opracowano wiele chwytów obezwładniających, tzw. \"dźwigni\", powszechnie wykorzystywanych przez służby mundurowe.",
    "Tatami to tradycyjna nazwa maty treningowej. To na nich odbywają się treningi oraz zawody z takich sztuk walki jak Karate czy Judo.",
    "Sambo (ros. самбо) to powstała w 1. połowie XX wieku rosyjska efektywna sztuka walki łącząca techniki judo z regionalnymi odmianami zapasów z terenu dawnego ZSRR. Jest uznawana za dyscyplinę sportową. Instruktaż sambo opracował w 1927 r. Władimir Spiridonow i stał się on podstawowym podręcznikiem walki wręcz dla Armii Czerwonej, Milicji i służb specjalnych.",
    "Jonini byli najbardziej doświadczoną grupą ninja. Szkolili młodszych i planowali misje, chociaż sami rzadko brali w nich udział.",
    "Iaido to sztuka walki kojarzona z płynnymi, kontrolowanymi ruchami miecza. W skład typowego pokazu Iaido wchodzi wyciągnięcie miecza z pochwy, cięcie, wytarcie krwi z ostrza i schowanie miecza w pochwie. Nie ma w iaido sparringów między adeptami tej sztuki.",
    "Ippon oznacza decyzję sędziowską o zakończeniu walki przed czasem i ogłoszeniu zwycięstwa jednego z zawodników w wyniku uzyskania pełnego punktu. Jest stosowany m.in. w judo, jujutsu, karate czy aikido. Sędzia ogłaszający decyzję ippon podnosi rękę do góry z wewnętrzną częścią dłoni skierowaną do przodu i wymawia słowa \"Ippon soremade!\" (np. w judo za czysty technicznie rzutu na plecy).",
    "Muay thai, czyli inaczej tajski boks, został stworzony najprawdopodobniej w Tajlandii. Początkowo służył do ochrony władcy. Skupia się głównie na uderzeniach kolanami oraz łokciami. W Polsce boks tajski zaczęto uprawiać w latach 90. XX w.",
    "Yabusame to japońskie łucznictwo konne, szczególnie popularne w okresie Kamakura (zrodziło się w XII wieku). Yabusame jest zaliczane do koryū-bujutsu, czyli tradycyjnych sztuk walki. Było stosowane nie tylko na wojnie, ale należało także do ulubionych konkurencji w zawodach rozgrywanych wśród samurajów. Jako widowisko rozrywkowe przetrwało do dzisiejszego dnia. Szczególnie duże i znane zawody odbywają się w Kamakurze w dniach 15-16 września.",
    "Shuriken to tzw. \"gwiazdka ninja\". Istniało  wiele wariantów tej broni, 4, 5, 6-ramienne (i więcej!). Shurikeny nie służyły do zabicia, ale do rozproszenia przeciwnika. Ostrza często były maczane w truciźnie, która miała dodatkowo uniemożliwić pościg.",
    "Bruce Lee początkowo trenował Wing Chun, tradycyjny system rozwoju fizycznego oraz walki związany z klasztorem Shaolin. Później, Bruce Lee odrzucił wiele z tradycyjnych wzorców, wprowadzając w to miejsce wiele technik zapożyczonych z innych źródeł.",
    "MMA to skrót od Mixed Martial Arts co oznacza \"mieszane sztuki walki\"",
    "Podczas antycznych igrzysk olimpijskich odbywała się konkurencja pankration, która swoimi zasadami przypomina dzisiejsze MMA"];

var lifeStyle = [
    "Twoja skóra waży dwa razy więcej niż twój mózg!",
    "Nieprzerwana czkawka może trwać najdłużej 65 lat",
    "Jeśli mężczyzna nie goliłby się przez całe życie jego broda miałaby długość 4 metrów",
    "U większości ludzi kciuk jest takiej samej długości, co ich nos",
    "Nasz kwas żołądkowy mógłby rozpuścić żyletkę",
    "Twoje ciało produkuje dziennie prawie litr śliny",
    "Nasze DNA jest w 50% podobne do DNA banana",
    "Strzelanie palców czy pleców, to pękanie bąbelków gazu w płynie otaczającym nasze stawy",
    "W trakcie kichania wszystkie ludzie narządy przestają na chwilę pracować",
    "Po dużym posiłku gorzej słyszymy",
    "Zjedzenie około 20 kwaśnych wiśni pomaga zwalczyć ból głowy",
    "Podczas oglądania TV spalamy średnio 1-2 kalorię na minutę",
    "Ludzie, którzy palą posiadają do 10 razy więcej zmarszczek od niepalących",
    "Jeden na 20 ludzi posiada dodatkowe żebro",
    "Brzeg (woj. dolnośląskie) jest prawdziwym zagłębiem stulatków. Mieszka ich tu około 30. Urodzeni na wschodzie i zahartowani ciężką pracą trzymają się dziarsko",
    "Pocałunek trwający minutę może spalić 26 kcal",
    "Dzieci karmione piersią posiadają zazwyczaj wyższe IQ",
    "W osiemnastym tygodniu ciąży u dziecka wykształcają się odciski palców.",
    "Codziennie ludzki żołądek produkuje 2 litry kwasu chlorowodorowego",
    "Śmiech jest lekarstwem dla duszy i ciała. Śmianie się uwalnia od stresów i napięć, pobudza pracę mózgu, wspomaga leczenie astmy i migreny, stanowi naturalny masaż tętnicy szyjnej.",
    "Słuchanie muzyki wpływa korzystnie na trawienie",
    "Stopy posiadają 250 000 gruczołów potowych",
    "Każdego dnia człowiek traci ok. 100 włosów",
    "Człowiek może przetrwać dłużej bez jedzenia niż bez snu. Bez jedzenia może przeżyć kilka tygodni bez snu ok. 10 dni.",
    "85% mózgu to woda.",
    "Twarz potrzebuje 17 mięśni aby wyrazić uśmiech i 43 aby wyrazić smutek.",
    "Włosy w nosie podczas życia rosną do 2 m. długości.",
    "Impulsy nerwowe z i do mózgu poruszają się z prędkością powyżej 280 km/h",
    "Truskawki zawierają więcej witaminy C niż cytryny czy grejpfruty, podobnie czerwona papryka.",
    "Borówki mogą pomagać w zwalczaniu zapalenia pęcherza moczowego i mają właściwości antybakteryjne.",
    "Bobu nie powinny w dużej ilości jeść osoby zażywające leki przeciwdepresyjne. Połączenie może doprowadzić do skoku ciśnienia.",
    "Cebula zapobiega powstawaniu choroby wieńcowej, ponieważ może obniżać poziom cholesterolu.",
    "Chili poprawia nastrój. Ostry smak wywołuje wydzielanie endorfin – hormonów szczęścia.",
    "Odpowiednia dieta, bogata w magnez, witaminę E i B6, może zmniejszyć dolegliwości menstruacyjne.",
    "Unikanie czekolady, cytrusów, serów i używek wpływa na zmniejszenie występowania i nasilenia bólów migrenowych.",
    "Herbata czarna pita podczas posiłku mięsnego powoduje ograniczenie wchłaniania żelaza do organizmu.",
    "Cholesterol zawarty w jajkach nie wpływa na podwyższenie cholesterolu całkowitego w organizmie.",
    "Dieta zawierająca produkty zasadotwórcze (np. mleko, warzywa) wspomaga rzucenie palenia papierosów, obniżając eliminację nikotyny z organizmu, co opóźnia powstawanie głodu nikotynowego.",
    "Tabliczka ciemnej czekolady (125g) zawiera więcej kofeiny niż filiżanka kawy instant"];
    
    module.exports = {sport: sport, lifeStyle: lifeStyle}